name: Sync to Hugging Face hub
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]


  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install git-lfs
        run: |
          sudo apt-get install git-lfs

      - name: Install Hugging Face CLI
        run: |
          pip install hf-lfs
      - name: Push to hub
        run: |
          echo "${{ secrets.HF_TOKEN }}" | huggingface-cli login
          git clone https://huggingface.co/spaces/thomas3737/car_team
          
          cp -r auto_cover_letter/* car_team/
          cd car_team
          git add .
          git commit -m "Update from GitHub repository"
          git push