name: Brain Lint with black

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auto_cover_letter
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: setup-python
        uses: actions/setup-python@v3
      - name: install black
        run: pip install black
      - name: lint
        run: black --check .
